Fallo al compilar (error con el bean)
Iagosevic/practica-1 pull request #4
Opened 2023-03-14 08:29 UTC by Iagosevic

2023-03-14 08:40 UTC, adriannsou requested changes
Como recomendación general, deberías separar las clases en paquetes (pe .controller, .repository) al hacer eso revisa la anotación @EnableJpaRepositories para buscar los repositorios en el paquete que corresponda.

2023-03-14 08:40 UTC, adriannsou commented on pom.xml
> +        <dependency>
Esta dependencia sobra, porque la pusiste?

2023-03-14 08:40 UTC, adriannsou commented on pom.xml
> +		<dependency>
Esta también

2023-03-14 08:40 UTC, adriannsou commented on src/main/java/com/qindel/practicas/practica1/AccessingDataJpaApplication.java
> +    public CommandLineRunner demo(JJOORepository repository) {
Esto sobra también, está bien para probar el ejemplo, pero se debería acceder desde el controller

2023-03-14 08:40 UTC, adriannsou commented on src/main/java/com/qindel/practicas/practica1/JJOORepository.java
> +@SpringBootApplication
Esta anotación sobra, solo se pone en la clase "main"

2023-03-14 08:40 UTC, adriannsou commented on src/main/java/com/qindel/practicas/practica1/AccessingDataJpaApplication.java
> +public class AccessingDataJpaApplication {
No podemos tener 2 clases "application" que nos arranquen la aplicación, ya tenemos la otra. Solo un "Application.java" con la anotación @SpringBootApplication por proyecto.

2023-03-14 09:48 UTC, Iagosevic commented on src/main/java/com/qindel/practicas/practica1/AccessingDataJpaApplication.java
> +    public CommandLineRunner demo(JJOORepository repository) {
Te refieres a que sobra la anotacion Bean o que sobra todo el metodo demo?

2023-03-15 12:21 UTC, adriannsou requested changes

2023-03-15 12:21 UTC, adriannsou commented on src/main/java/com/qindel/practicas/practica1/Practica1Application.java
> +@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class })
porqué esta exclusión?

2023-03-15 12:21 UTC, adriannsou commented on src/main/java/com/qindel/practicas/practica1/Practica1Application.java
> +//@EnableJpaRepositories("com.qindel.practicas.practica1")
tienes que activarla, con el paquete donde tienes los repositorios

2023-03-15 12:21 UTC, adriannsou commented on src/main/java/com/qindel/practicas/practica1/controllers/JJOOController.java
> +    public ResponseEntity<List<JJOOEntity>> consultarJuegosOlimpicos() {
aquí no debería devolver el wrapper?

2023-03-21 12:41 UTC, adriannsou requested changes
Que pasa con todas esas clases Mapper y Servicios y demás? No son necesarias para esta tarea, quítalas también

2023-03-21 12:41 UTC, adriannsou commented on src/main/java/com/qindel/practicas/practica1/Practica1Application.java
> +@EntityScan("com.qindel.practicas.practica1.*")
el paquete donde están las entites no está bien, te falta .entities

2023-03-21 12:41 UTC, adriannsou commented on src/main/java/com/qindel/practicas/practica1/Practica1Application.java
> +@SpringBootApplication(exclude={DataSourceAutoConfiguration.class})
porque este exclude? así se pierde la configuración de spring boot para acceder a la base de datos

2023-03-21 12:41 UTC, adriannsou commented on src/main/java/com/qindel/practicas/practica1/Practica1Application.java
> -@SpringBootApplication
por aquí falta la anotación para decirle donde tiene que buscar los repositorios, porqué la quitaste?

2023-03-21 12:41 UTC, adriannsou commented on pom.xml
> +        <dependency>
estas dependencias no deberías meterlas, son dependencias de hibernate. con el starter de jpa debería bastar, quítalas

2023-03-27 06:54 UTC, adriannsou requested changes
Lo que te puse para el controlador de ciudades, aplicarlo para todos.

2023-03-27 06:54 UTC, adriannsou commented on src/main/java/com/qindel/practicas/practica1/controllers/CiudadController.java
> +    @GetMapping("/all")
normalmente, /ciudades ya devuelve todas las ciudades, /ciudades/all, no es un recurso que se exponga, ya que /all sería como la operación. En nomeclatura REST, la operación viene dada por el método (GET, POST, etc), no por la ruta

2023-03-27 06:54 UTC, adriannsou commented on src/main/java/com/qindel/practicas/practica1/controllers/CiudadController.java
> +    @GetMapping("/{idciudad}")
kebab-case (/id-ciudad)

2023-03-27 06:54 UTC, adriannsou commented on src/main/java/com/qindel/practicas/practica1/controllers/CiudadController.java
> +    @GetMapping("/ciudad/{nombreciudad}")
kebab-case. Normalmente las operaciones REST se hacen sobre una colección (en este caso /ciudades). La operación en /ciudades/ciudad/... sería repetitivo. En general, un filtro en el path (el nombre) no seria algo correcto, pero ya que se trata de un "id único" el nombre del país, podría estar bien.
Lo normal sería /ciudades/1231 (1231 es el id único de la ciudad).

2023-03-28 06:14 UTC, adriannsou approved these changes

2023-03-28 06:40 UTC, merged